steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--build-arg', 'REPO_NAME=$REPO_NAME', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
