steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--build-arg', 'REPO_NAME=$REPO_NAME', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/$REPO_NAME'
  - 'app=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
