replicaCount: 3

ingress:
  annotations:
     nginx.ingress.kubernetes.io/secure-backends: 'false'

  enableExternalDNS: true
  
  host: "filled.by.cloudbuild"
  paths:
    - /
      
  acme:
    issuer:
      name: letsencrypt-prod
      kind: cluster-issuer


resources:
   requests:
    cpu: 100m
    memory: 128Mi
   limits:
    cpu: 400m
    memory: 256Mi
