# Declare variables to be passed into your templates.

replicaCount: 3

ingress:
  enabled: true
  enableExternalDNS: false

  ## Additional Ingress annotations
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/secure-backends: 'false'

  # This chart is optimized for a service living on a single hostname
  # This allows features like external-dns and certmanager to work out of the box
  host: "app.example.com"
  # All paths will map to ingress.host
  paths:
    - /

  ## Ingress TLS configuration will be overridden if acme.enabled is true
  ## Otherwise, secrets must be manually created in the namespace
  ##
  # tls:
  #   - secretName: foo-tls
  #     hosts:
  #       - foo.domain.com

  # Currently supports certmanager only
  acme:
    issuer:
      name: letsencrypt-staging
      kind: clusterIssuer


resources:
   requests:
    cpu: 100m
    memory: 128Mi
   limits:
    cpu: 400m
    memory: 256Mi
