replicaCount: 3

ingress:
  annotations:
     nginx.ingress.kubernetes.io/secure-backends: 'false'

  enableExternalDNS: true
  
  acme:
    issuer:
      name: letsencrypt-staging
      kind: clusterIssuer


resources:
   requests:
    cpu: 100m
    memory: 128Mi
   limits:
    cpu: 400m
    memory: 256Mi
