# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

ingress:
  enabled: true

  ## Ingress annotations
  ##
  annotations:
     external-dns.alpha.kubernetes.io/hostname: "app.example.com"
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/secure-backends: 'false'
     kubernetes.io/tls-acme: 'false'


  ## Ingress path
  ## Ignored if hosts: is defined
  path: /

  ## Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  # tls:
  #   - secretName: foo-tls
  #     hosts:
  #       - foo.domain.com


resources:
   requests:
    cpu: 100m
    memory: 128Mi
   limits:
    cpu: 400m
    memory: 256Mi
