{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

{{- with .Values.ingress -}}

  {{- if or .annotations .enableExternalDNS .acme }}
  annotations:
  {{- if .enableExternalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .host }}
  {{- end }}
  {{- if .acme }}
    certmanager.k8s.io/{{ .acme.issuer.kind }}: {{ .acme.issuer.name }}
  {{- end }}
{{ toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          {{- range $path := .paths }}
          - path: {{ $path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- end }}
      {{- if .host }}
      host: {{ .host }}
      {{- end }}
  {{- if .tls }}
  tls:
{{ toYaml .tls | indent 4 }}
  {{- else if .acme }}
  tls:
    - hosts:
      - {{ .host }}
      secretName: {{.host}}-{{.acme.issuer.name}}-tls
  {{- end }}

{{- end -}}

{{- end -}}
