{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

{{- with .Values.ingress }}

  {{- if or .annotations .enableExternalDNS .acme }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end -}}

  {{- if .enableExternalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .host }}
  {{- end -}}
  {{- if .acme.issuer }}
    certmanager.k8s.io/{{ .acme.issuer.kind }}: {{ .acme.issuer.name }}
  {{- end -}}

spec:
  rules:
  {{- range $path := .paths }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ $path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end -}}
  {{- if .tls }}
  tls:
{{ toYaml .tls | indent 4 }}
  {{- else if .acme -}}
  tls:
    secretName: {{.host}}-{{.acme.issuer.name}}-tls
      hosts:
      - {{ .host }}
  {{- end -}}

{{- end -}}

{{- end -}}
