# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/project_id/repository
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

  ## Ingress annotations
  ##
  annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/secure-backends: 'true'

  ## This chart is optimized for a service living on a single hostname
  ## This allows features like external-dns and certmanager to work out of the box
  ## All paths will map to ingress.host if set

  # host: "app.example.com"
  paths:
    - /

  ## Ingress TLS configuration will be overridden if acme.enabled is true
  ## Otherwise, secrets must be manually created in the namespace
  ##
  # tls:
  #   - hosts:
  #       - foo.domain.com
  #     secretName: foo-tls

  ## Add annotation for external-dns
  enableExternalDNS: false

  ## Currently supports certmanager only
  #  acme:
  #    issuer:
  #      name: letsencrypt-staging
  #      kind: clusterIssuer

resources: {}
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi
  #  limits:
  #    cpu: 400m
  #    memory: 256Mi

nodeSelector: {}

tolerations: []

antiAffinity: "soft"
# additionalAffinities:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 50
#         preference:
#           matchExpressions:
#             - key: cloud.google.com/gke-preemptible
#               operator: In
#               values:
#                 - "true"

livenessProbe:
  path: /healthz
