# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  # set by cloudbuild
  # repository: gcr.io/$PROJECT_ID/$REPO_NAME
  # tag: $SHORT_SHA
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

  ## Ingress annotations
  ##
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/secure-backends: "true"
  #   kubernetes.io/tls-acme: 'true'

  ## Ingress path
  ## Ignored if hosts: is defined
  path: /

  ## Kubernetes Dashboard Ingress hostnames
  ## May be omitted if only one host
  ## Not sure if correct -AF 2018
  # hosts:
    # - foo.domain.com
      # path: /blah

  ## Ingress TLS configuration
  ## Secrets must be manually created in the namespace
  ##
  # tls:
  #   - secretName: foo-tls
  #     hosts:
  #       - foo.domain.com


resources:
   requests:
    cpu: 100m
    memory: 128Mi
   limits:
    cpu: 400m
    memory: 256Mi

nodeSelector: {}

tolerations: []

antiAffinity: "soft"
# additionalAffinities:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 50
#         preference:
#           matchExpressions:
#             - key: cloud.google.com/gke-preemptible
#               operator: In
#               values:
#                 - "true"

livenessProbe:
  path: /healthz
